name: Deploy to EC2 (Staging)

on:
  push:
    branches:
      - "main"

jobs:
  deploy-staging:
    name: Release to staging
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_STORAGE_PATH: ${{ secrets.STORAGE_PATH }}
          envkey_BUILD_ENVIRONMENT: ${{ secrets.BUILD_ENVIRONMENT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Run build:prod
        run: npm run build:prod --if-present

      - name: Copy files to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOSTNAME }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.DEPLOY_PATH }}
          ARGS: -rlgoDzvcO -i
